version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  reviewers:
  - michaelgracious
  assignees:
  - michaelgracious
  ignore:
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/cache
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/config
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
